on:
  push:
    branches:
    -  main
  pull_request:

env:
  FORCE_COLOR: 1
  PY_COLORS: 1

defaults:
  run:
    shell: bash

jobs:
  qa:
    if: ${{ github.actor != 'dependabot[bot]' && !cancelled() }}
    name: ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ['3.13']
    steps:
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
    - uses: astral-sh/setup-uv@023eb7875fa1caa15814da58d1df7350f8fb1fd9
      with:
        enable-cache: true
    - name: Install
      id: install
      run: uv sync --frozen --python ${{matrix.version}}
    - name: Lint
      if: ${{ !cancelled() && steps.install.conclusion == 'success' }}
      run: uv run --no-sync --frozen --python ${{matrix.version}} ruff check .
    - name: Check type safety
      if: ${{ !cancelled() && steps.install.conclusion == 'success' }}
      run: uv run --no-sync --frozen --python ${{matrix.version}} mypy .
    - name: Run tests
      if: ${{ !cancelled() && steps.install.conclusion == 'success' }}
      run: uv run --no-sync --frozen --python ${{matrix.version}} pytest -svv
